apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qa-app
  template:
    metadata:
      labels:
        app: qa-app
    spec:
      containers:
      - name: qa-app
        image: sudarshan2244/multi-env-app:latest
        ports:
        - containerPort: 3000
